config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'links', to: 'links#index'
  get 'search', to: 'pages#search'
  get 'add', to: 'pages#add'
  post 'search', to: 'links#search'
  get 'category', to: 'categories#new'
  
  post 'category', to: 'categories#create'

  resources :users do
    resources :links
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  validates(:name, presence: true)

end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_one :category

  validates :link, presence: true, :format => URI::regexp(%w(http https))
  
  def self.per_page
    5
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :links, dependent: :destroy
	has_many :categories, dependent: :destroy

	before_save { self.email = email.downcase }
	validates(:name, presence: true, length: {maximum: 50})
	
	has_secure_password
	validates(:password, presence: true, length: {minimum: 6})

	def User.digest(string)
	   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	   BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include ApplicationHelper

  def not_found
  	raise ActionController::RoutingError.new('Not Found')
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	def new
		@category = Category.new
	end

	def create
		user = current_user
		category = user.categories.new(category_params)

		if category.save
			flash[:success] = "Category Saved"
			render template: "pages/add"
		else
			flash[:warning] = "Fail, Try save category again"
			redirect_to category_path
		end

	end

	private
	def category_params
		params.require(:category).permit(:name)
	end

end

app/controllers/links_controller.rb
require 'open-uri'

class LinksController < ApplicationController

	def index
		@user = User.find(current_user)
		@links = @user.links.paginate(page: params[:page])
	end
	
	def create
		@user = User.find(params[:user_id])
		link = @user.links.new(link_params)
		if link.save
			begin
				object = LinkThumbnailer.generate(link.link)
				open('app/assets/images/'+link.id.to_s+".png", 'wb') do |file|
					file << open(object.images.first.src.to_s).read
				end
				link.update_attributes(title: object.title ,path: link.id.to_s+".png" )
			rescue => e
				link.update_attributes(title: link.link ,path: "default-news-image.jpg" )
			end

				flash[:success] = "Link Saved"
				redirect_to links_path
			
		else
			flash[:warning] = "Fail, Try copy link again"
			render template: "pages/add"
		end
	end

	def destroy
		@user = User.find(params[:user_id])
		@link = @user.links.find(params[:id])
		@link.destroy
		redirect_to links_path
	end

	def search
		user = current_user
		if params[:options][:id] == ""
			@links = user.links.where("title like ?", "%#{params[:options][:title]}%").paginate(page: params[:page])
		else
			@links = user.links.where("title like ? and category_id = ?", "%#{params[:options][:title]}%", params[:options][:id] ).paginate(page: params[:page])						
		end
		render 'index'
	end

	private
	def link_params
		params.require(:link).permit(:title, :link,:category_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    user = current_user
  	if logged_in? && user.id.to_s == params[:id] 
    	@user = User.find(params[:id])
	  end
  end

  def create
  	@user = User.new(user_params)
    begin
      	if @user.save
      		log_in @user
      		flash[:success] = "Start save links for study later"
      		redirect_to @user
      	else
          flash[:warning] = "Create Fail, Try Again"
      		render 'new'
       	end
    rescue => e
      flash[:warning] = "Email already exists"
      render 'new'
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  	end
end

app/helpers/application_helper.rb
require 'open-uri'

module ApplicationHelper

	def category_name(id)
		if id != nil
			Category.find(id).name
		end
	end

	def category_options_ids
		ids_arr = @current_user.categories.pluck(:id)

		names_arr = []
		ids_arr.each do |id|
			if !id.nil?
				names_arr.push(Category.find(id).name)
			end
		end

		return names_arr.zip ids_arr
	end

	def thumbnail_link(id)
		path = 'app/assets/images/'+id.to_s+'.png'

		if File.exist?(path)
			id.to_s+'.png'
		else
			object = LinkThumbnailer.generate('http://stackoverflow.com')
			open(path, 'wb') do |file|
		   		file << open(object.images.first.src.to_s).read
		 	end
		 	id.to_s+'.png'
		end

	end 

	def thumbnail_download(link)
		object = LinkThumbnailer.generate(link.link)

		open('app/assets/images/'+link.id.to_s+".png", 'wb') do |file|
			file << open(object.images.first.src.to_s).read
		end

	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
  	!current_user.nil?
  end
	
  def log_out
  	session.delete(:user_id)
  	@current_user = nil
  end  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1>Add a new Category</h1>
  <%= form_for(@category, url: category_path, html: {class: "form-horizontal"}) do |f| %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name , class: 'form-control' %>
    </div>

  <div class="form-group ">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Project Developed for Jera Intership exam <a href="http://jera.com.br/">Jera Website</a>
    by <a href="#">Sergio Soares</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Study Later", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "Home", root_path %></li>
       <% if logged_in? %>
       <li><%= link_to "Links", links_path %></li>
       <li><%= link_to "Add Links", add_path %></li>
       <li><%= link_to "Search", search_path %></li>

            
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyLater</title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
     <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for([@current_user, @current_user.links.build], html: {class: "form-horizontal"}) do |f| %>

    <div class="form-group">
      <%= f.label :link %><br>
      <%= f.text_field :link, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :category %>-
    <%= f.select :category_id, category_options_ids, {include_blank: true, class: "form-control"} %>
    <%= link_to "Add new category", category_path %>
    </div>
    

  <div class="form-group ">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/links/_link.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-xs-3 col-md-2 text-center">
                    <%= image_tag(link.path, size: "120x120", alt: "Edit Entry",  class: "img-rounded img-responsive") %>
                        
                    </div>
                    <div class="col-xs-9 col-md-9 section-box">
                        <a href=<%= link.link %> target="_blank">
                            <h3>Title: <%= link.title %> 
                                <span class="separator">|</span> 
                                Category: <%= category_name(link.category_id) %>
                            </h3>
                        </a>
                        <hr />
                        <div class="row rating-desc">
                            <div class="col-md-12">
                            <%= link_to 'Readed', [link.user, link],
                                          method: :delete,
                                          data: { confirm: 'Are you sure already read?' }, class:"glyphicon glyphicon-bookmark" %>
                               <span class="separator">|</span>
                                <%= link_to 'Enter-link', link.link, class:"glyphicon glyphicon-share-alt",  target:"_blank"%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/links/_search.html.erb
<%= form_for(:options, url: search_path, html: {class: "form-horizontal"}) do |f| %>

	<div class="form-group">
		<%= f.label :title %><br>
		<%= f.text_field :title , class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :category %>
		<%= f.select :id, category_options_ids, {include_blank: true, class: "form-control"} %>
	</div>
	
  	<div class="form-group ">
		<%= f.submit class: 'btn btn-primary'%>
	</div>
<% end %>

app/views/links/index.html.erb
<h1>Links</h1>

<ul class="list-group">
  <% @links.each do |link| %>
    <%= render link %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/pages/add.html.erb
<% if logged_in? %>
	<h1>Add a link to study</h1>
	<%= render 'links/form' %>
<%end %>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Study Later - This is a APP to save link for future study </h1>
	<% if !logged_in? %>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	<%= link_to "Loggin now!", login_path, class: "btn btn-lg btn-primary" %>
	<% end %>
</div>

<% if logged_in? %>
<div class="row">
	<div class="col-md-4">
	<%= link_to "See all Links", links_path, class:"btn btn-default btn-lg btn-block btn-huge"%>
	</div>

	<div class="col-md-4">
		<%= link_to "Add Links", add_path, class:"btn btn-default btn-lg btn-block btn-huge"%>
	</div>

	<div class="col-md-4">
	<%= link_to "Search Links", search_path, class:"btn btn-default btn-lg btn-block btn-huge"%>
	</div>
</div>


<% end %>

app/views/pages/search.html.erb
<% if logged_in? %>
	<h1>Search links</h1>
	<%= render 'links/search' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="center ">
	<div class="container-fluid well ">
		<div class="row-fluid">
			<div class="col-md-4" >
				<img src="https://secure.gravatar.com/avatar/" >
			</div>

			<div class="col-md-4">
				<h1> <%= @user.name %></h3>
				<h2>Email: <%= @user.email%></h2>
				<h2>Links for read:  <%= @user.links.count%> <%= link_to "See Links", links_path %></h2>
				<h2>Categories in use: <%= @user.categories.count%> <%= link_to "Add new category", category_path %></h2>

				<%= link_to "Alter profile", edit_user_path(current_user),class: "btn btn-lg btn-primary"  %>
			</div>
		</div>
	</div>